# install packages
install.packages("data.table")
install.packages("stringi")
install.packages("DBI")
install.packages("RPostgres")
install.packages("dotenv")
install.packages("slackr")
install.packages("rjson")
install.packages("httr")
install.packages("zoo")
install.packages("tidyverse")